[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.98.1"
reqwest = { version = "0.11", features = ["blocking"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }